import 'package:flutter/material.dart';

import '../../core/constants/app_colors.dart';

/// Domain entity representing battery information
/// for Windows desktop.
///
/// Combines real-time data from [battery_plus] with
/// health data parsed from the Windows battery report
/// generated by `powercfg /batteryreport`.
class BatteryInfo {
  /// Current charge level (0-100) from battery_plus.
  final int level;

  /// Whether the device is currently charging.
  final bool isCharging;

  /// Design capacity in mWh (factory spec).
  final int designCapacityMwh;

  /// Full charge capacity in mWh (current max).
  final int fullChargeCapacityMwh;

  /// Battery name from the report (e.g. "DELL 2X39G").
  final String name;

  /// Battery manufacturer (e.g. "LGC-LGC7.78").
  final String manufacturer;

  /// Battery serial number.
  final String serialNumber;

  /// Battery chemistry (e.g. "LION", "LiP").
  final String chemistry;

  /// Cycle count, if available.
  final String cycleCount;

  const BatteryInfo({
    required this.level,
    required this.isCharging,
    required this.designCapacityMwh,
    required this.fullChargeCapacityMwh,
    this.name = 'Unknown',
    this.manufacturer = 'Unknown',
    this.serialNumber = 'Unknown',
    this.chemistry = 'Unknown',
    this.cycleCount = '-',
  });

  /// Computes battery health as a percentage.
  /// Returns 0 if design capacity is zero.
  double get healthPercent {
    if (designCapacityMwh <= 0) return 0;
    final health = (fullChargeCapacityMwh * 100.0) / designCapacityMwh;
    return health.clamp(0, 100);
  }

  /// Returns a translation key for the health status.
  /// Use `AppStrings.tr(info.healthStatus)` in the UI.
  String get healthStatus {
    final h = healthPercent;
    if (h >= 90) return 'health_excellent';
    if (h >= 70) return 'health_good';
    if (h >= 50) return 'health_moderate';
    if (h >= 30) return 'health_warning';
    return 'health_critical';
  }

  /// Returns a color representing the health status.
  Color get healthColor => AppColors.getHealthColor(healthPercent);

  /// Formats a capacity value to a human-readable string.
  /// Example: 42920 → "42,920 mWh"
  static String formatCapacity(int mwh) {
    if (mwh <= 0) return '-';
    final str = mwh.toString();
    final buffer = StringBuffer();
    for (var i = 0; i < str.length; i++) {
      if (i > 0 && (str.length - i) % 3 == 0) {
        buffer.write(',');
      }
      buffer.write(str[i]);
    }
    return '$buffer mWh';
  }
}
